// Code generated by counterfeiter. DO NOT EDIT.
package gohealth

import (
	"sync"

	"github.com/InVisionApp/go-health"
)

type FakeILogger struct {
	DebugStub        func(msg string, args map[string]interface{})
	debugMutex       sync.RWMutex
	debugArgsForCall []struct {
		msg  string
		args map[string]interface{}
	}
	InfoStub        func(msg string, args map[string]interface{})
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
		msg  string
		args map[string]interface{}
	}
	WarnStub        func(msg string, args map[string]interface{})
	warnMutex       sync.RWMutex
	warnArgsForCall []struct {
		msg  string
		args map[string]interface{}
	}
	ErrorStub        func(msg string, args map[string]interface{})
	errorMutex       sync.RWMutex
	errorArgsForCall []struct {
		msg  string
		args map[string]interface{}
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeILogger) Debug(msg string, args map[string]interface{}) {
	fake.debugMutex.Lock()
	fake.debugArgsForCall = append(fake.debugArgsForCall, struct {
		msg  string
		args map[string]interface{}
	}{msg, args})
	fake.recordInvocation("Debug", []interface{}{msg, args})
	fake.debugMutex.Unlock()
	if fake.DebugStub != nil {
		fake.DebugStub(msg, args)
	}
}

func (fake *FakeILogger) DebugCallCount() int {
	fake.debugMutex.RLock()
	defer fake.debugMutex.RUnlock()
	return len(fake.debugArgsForCall)
}

func (fake *FakeILogger) DebugArgsForCall(i int) (string, map[string]interface{}) {
	fake.debugMutex.RLock()
	defer fake.debugMutex.RUnlock()
	return fake.debugArgsForCall[i].msg, fake.debugArgsForCall[i].args
}

func (fake *FakeILogger) Info(msg string, args map[string]interface{}) {
	fake.infoMutex.Lock()
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
		msg  string
		args map[string]interface{}
	}{msg, args})
	fake.recordInvocation("Info", []interface{}{msg, args})
	fake.infoMutex.Unlock()
	if fake.InfoStub != nil {
		fake.InfoStub(msg, args)
	}
}

func (fake *FakeILogger) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *FakeILogger) InfoArgsForCall(i int) (string, map[string]interface{}) {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return fake.infoArgsForCall[i].msg, fake.infoArgsForCall[i].args
}

func (fake *FakeILogger) Warn(msg string, args map[string]interface{}) {
	fake.warnMutex.Lock()
	fake.warnArgsForCall = append(fake.warnArgsForCall, struct {
		msg  string
		args map[string]interface{}
	}{msg, args})
	fake.recordInvocation("Warn", []interface{}{msg, args})
	fake.warnMutex.Unlock()
	if fake.WarnStub != nil {
		fake.WarnStub(msg, args)
	}
}

func (fake *FakeILogger) WarnCallCount() int {
	fake.warnMutex.RLock()
	defer fake.warnMutex.RUnlock()
	return len(fake.warnArgsForCall)
}

func (fake *FakeILogger) WarnArgsForCall(i int) (string, map[string]interface{}) {
	fake.warnMutex.RLock()
	defer fake.warnMutex.RUnlock()
	return fake.warnArgsForCall[i].msg, fake.warnArgsForCall[i].args
}

func (fake *FakeILogger) Error(msg string, args map[string]interface{}) {
	fake.errorMutex.Lock()
	fake.errorArgsForCall = append(fake.errorArgsForCall, struct {
		msg  string
		args map[string]interface{}
	}{msg, args})
	fake.recordInvocation("Error", []interface{}{msg, args})
	fake.errorMutex.Unlock()
	if fake.ErrorStub != nil {
		fake.ErrorStub(msg, args)
	}
}

func (fake *FakeILogger) ErrorCallCount() int {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return len(fake.errorArgsForCall)
}

func (fake *FakeILogger) ErrorArgsForCall(i int) (string, map[string]interface{}) {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return fake.errorArgsForCall[i].msg, fake.errorArgsForCall[i].args
}

func (fake *FakeILogger) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.debugMutex.RLock()
	defer fake.debugMutex.RUnlock()
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	fake.warnMutex.RLock()
	defer fake.warnMutex.RUnlock()
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeILogger) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ health.ILogger = new(FakeILogger)
